#ifndef __MC_ID_H_INCLUDED__
#define __MC_ID_H_INCLUDED__

#include <stdint.h>

enum mc_block_id {
    block_minecraft__air = 0,

    block_minecraft__stone = 1,
    block_minecraft__granite = 2,
    block_minecraft__polished_granite = 3,
    block_minecraft__diorite = 4,
    block_minecraft__polished_diorite = 5,
    block_minecraft__andesite = 6,
    block_minecraft__polished_andesite = 7,
    block_minecraft__grass_block = 8,
    block_minecraft__dirt = 9,
    block_minecraft__coarse_dirt = 10,
    block_minecraft__podzol = 11,
    block_minecraft__cobblestone = 12,
    block_minecraft__infested_stone = 232,
    block_minecraft__infested_cobblestone = 233,
    block_minecraft__infested_stone_bricks = 234,
    block_minecraft__infested_mossy_stone_bricks = 235,
    block_minecraft__infested_cracked_stone_bricks = 236,
    block_minecraft__infested_chiseled_stone_bricks = 237,

    block_minecraft__oak_planks = 13,
    block_minecraft__spruce_planks = 14,
    block_minecraft__birch_planks = 15,
    block_minecraft__jungle_planks = 16,
    block_minecraft__acacia_planks = 17,
    block_minecraft__dark_oak_planks = 18,
    block_minecraft__oak_sapling = 19,
    block_minecraft__spruce_sapling = 20,
    block_minecraft__birch_sapling = 21,
    block_minecraft__jungle_sapling = 22,
    block_minecraft__acacia_sapling = 23,
    block_minecraft__dark_oak_sapling = 24,
    block_minecraft__bedrock = 25,

    //TODO flowing water and lava block
    block_minecraft__flowing_water = 26,
    block_minecraft__flowing_lava = 28,

    block_minecraft__water = 26,
    block_minecraft__lava = 28,
    block_minecraft__ice = 185,
    block_minecraft__glass = 67,

    // block_minecraft__stained_glass = 95,

    block_minecraft__white_stained_glass = 206,
    block_minecraft__orange_stained_glass = 207,
    block_minecraft__magenta_stained_glass = 208,
    block_minecraft__light_blue_stained_glass = 209,
    block_minecraft__yellow_stained_glass = 210,
    block_minecraft__lime_stained_glass = 211,
    block_minecraft__pink_stained_glass = 212,
    block_minecraft__gray_stained_glass = 213,
    block_minecraft__light_gray_stained_glass = 214,
    block_minecraft__cyan_stained_glass = 215,
    block_minecraft__purple_stained_glass = 216,
    block_minecraft__blue_stained_glass = 217,
    block_minecraft__brown_stained_glass = 218,
    block_minecraft__green_stained_glass = 219,
    block_minecraft__red_stained_glass = 220,
    block_minecraft__black_stained_glass = 221,

    block_minecraft__sand = 28,
    block_minecraft__red_sand = 29,

    block_minecraft__gravel = 30,
    block_minecraft__gold_ore = 31,
    block_minecraft__iron_ore = 32,
    block_minecraft__coal_ore = 33,

    block_minecraft__nether_gold_ore = 34,

    block_minecraft__oak_log = 35,
    block_minecraft__spruce_log = 36,
    block_minecraft__birch_log = 37,
    block_minecraft__jungle_log = 38,
    block_minecraft__acacia_log = 39,
    block_minecraft__dark_oak_log = 40,

    block_minecraft__stripped_oak_log = 46,
    block_minecraft__stripped_spruce_log = 41,
    block_minecraft__stripped_birch_log = 42,
    block_minecraft__stripped_jungle_log = 43,
    block_minecraft__stripped_acacia_log = 44,
    block_minecraft__stripped_dark_oak_log = 45,

    block_minecraft__oak_wood = 47,
    block_minecraft__spruce_wood = 48,
    block_minecraft__birch_wood = 49,
    block_minecraft__jungle_wood = 50,
    block_minecraft__acacia_wood = 51,
    block_minecraft__dark_oak_wood = 52,
    block_minecraft__stripped_oak_wood = 53,
    block_minecraft__stripped_spruce_wood = 54,
    block_minecraft__stripped_birch_wood = 55,
    block_minecraft__stripped_jungle_wood = 56,
    block_minecraft__stripped_acacia_wood = 57,
    block_minecraft__stripped_dark_oak_wood = 58,

    block_minecraft__oak_leaves = 59,
    block_minecraft__spruce_leaves = 60,
    block_minecraft__birch_leaves = 61,
    block_minecraft__jungle_leaves = 62,
    block_minecraft__acacia_leaves = 63,
    block_minecraft__dark_oak_leaves = 64,

    block_minecraft__sponge = 65,
    block_minecraft__wet_sponge = 66,
    block_minecraft__lapis_ore = 68,
    block_minecraft__lapis_block = 69,

    block_minecraft__sandstone = 71,
    block_minecraft__chiseled_sandstone = 72,
    block_minecraft__cut_sandstone = 73,

    block_minecraft__noteblock = 74,

    block_minecraft__white_bed = 75,
    block_minecraft__orange_bed = 76,
    block_minecraft__magenta_bed = 77,
    block_minecraft__light_blue_bed = 78,
    block_minecraft__yellow_bed = 79,
    block_minecraft__lime_bed = 80,
    block_minecraft__pink_bed = 81,
    block_minecraft__gray_bed = 82,
    block_minecraft__light_gray_bed = 83,
    block_minecraft__cyan_bed = 84,
    block_minecraft__purple_bed = 85,
    block_minecraft__blue_bed = 86,
    block_minecraft__brown_bed = 87,
    block_minecraft__green_bed = 88,
    block_minecraft__red_bed = 89,
    block_minecraft__black_bed = 90,

    block_minecraft__powered_rail = 91,
    block_minecraft__detector_rail = 92,

    block_minecraft__sticky_piston = 93,
    block_minecraft__piston = 100,
    block_minecraft__piston_head = 101,

    block_minecraft__cobweb = 94,

    block_minecraft__dead_bush = 97,
    block_minecraft__grass = 95,
    block_minecraft__fern = 96,
    block_minecraft__tall_grass = 414,
    block_minecraft__large_fern = 415,

    block_minecraft__white_wool = 102,
    block_minecraft__orange_wool = 103,
    block_minecraft__magenta_wool = 104,
    block_minecraft__light_blue_wool = 105,
    block_minecraft__yellow_wool = 106,
    block_minecraft__lime_wool = 107,
    block_minecraft__pink_wool = 108,
    block_minecraft__gray_wool = 109,
    block_minecraft__light_gray_wool = 110,
    block_minecraft__cyan_wool = 111,
    block_minecraft__purple_wool = 112,
    block_minecraft__blue_wool = 113,
    block_minecraft__brown_wool = 114,
    block_minecraft__green_wool = 115,
    block_minecraft__red_wool = 116,
    block_minecraft__black_wool = 117,

    block_minecraft__poppy = 120,
    block_minecraft__blue_orchid = 121,
    block_minecraft__allium = 122,
    block_minecraft__azure_bluet = 123,
    block_minecraft__red_tulip = 124,
    block_minecraft__orange_tulip = 125,
    block_minecraft__white_tulip = 126,
    block_minecraft__pink_tulip = 127,
    block_minecraft__oxeye_daisy = 128,
    block_minecraft__dandelion = 119,
    block_minecraft__wither_rose = 130,
    block_minecraft__cornflower = 129,
    block_minecraft__lily_of_the_valley = 131,

    block_minecraft__brown_mushroom = 132,
    block_minecraft__red_mushroom = 133,

    block_minecraft__gold_block = 134,
    block_minecraft__iron_block = 135,

    block_minecraft__oak_slab = 452,
    block_minecraft__spruce_slab = 453,
    block_minecraft__birch_slab = 454,
    block_minecraft__jungle_slab = 455,
    block_minecraft__acacia_slab = 456,
    block_minecraft__dark_oak_slab = 457,
    block_minecraft__petrified_oak_slab = 462,
    block_minecraft__stone_slab = 458,
    block_minecraft__sandstone_slab = 460,
    block_minecraft__cobblestone_slab = 463,
    block_minecraft__brick_slab = 464,
    block_minecraft__stone_brick_slab = 465,
    block_minecraft__nether_brick_slab = 466,
    block_minecraft__quartz_slab = 467,
    block_minecraft__red_sandstone_slab = 468,
    block_minecraft__purpur_slab = 470,
    block_minecraft__prismarine_slab = 386,
    block_minecraft__dark_prismarine_slab = 388,
    block_minecraft__prismarine_brick_slab = 387,
    block_minecraft__andesite_slab = 650,
    block_minecraft__diorite_slab = 653,
    block_minecraft__granite_slab = 649,
    block_minecraft__polished_andesite_slab = 652,
    block_minecraft__polished_diorite_slab = 644,
    block_minecraft__polished_granite_slab = 641,
    block_minecraft__red_nether_brick_slab = 651,
    block_minecraft__smooth_sandstone_slab = 647,
    block_minecraft__cut_sandstone_slab = 461,
    block_minecraft__smooth_red_sandstone_slab = 642,
    block_minecraft__cut_red_sandstone_slab = 469,
    block_minecraft__end_stone_brick_slab = 646,
    block_minecraft__mossy_cobblestone_slab = 645,
    block_minecraft__mossy_stone_brick_slab = 643,
    block_minecraft__smooth_quartz_slab = 648,
    block_minecraft__smooth_stone_slab = 459,
    block_minecraft__crimson_slab = 706,
    block_minecraft__warped_slab = 707,
    block_minecraft__polished_blackstone_brick_slab = 751,
    block_minecraft__blackstone_slab = 746,
    block_minecraft__polished_blackstone_slab = 756,






    block_minecraft__brick = 136,
    block_minecraft__tnt = 137,
                
    block_minecraft__bookshelf = 138,
    block_minecraft__mossy_cobblestone = 139,
    block_minecraft__obsidian = 140,

    block_minecraft__torch = 141,
    block_minecraft__wall_torch = 142,
    block_minecraft__redstone_torch = 181,
    block_minecraft__redstone_wall_torch = 182,
    block_minecraft__soul_torch = 198,
    block_minecraft__soul_wall_torch = 199,

    block_minecraft__fire = 143,
    block_minecraft__spawner = 145,

    block_minecraft__oak_stairs = 146,
    block_minecraft__cobblestone_stairs = 164,
    block_minecraft__brick_stairs = 251,
    block_minecraft__stone_brick_stairs = 252,
    block_minecraft__nether_brick_stairs = 257,
    block_minecraft__sandstone_stairs = 268,
    block_minecraft__spruce_stairs = 274,
    block_minecraft__birch_stairs = 275,
    block_minecraft__jungle_stairs = 276,
    block_minecraft__quartz_stairs = 340,
    block_minecraft__acacia_stairs = 375,
    block_minecraft__dark_oak_stairs = 376,
    block_minecraft__red_sandstone_stairs = 451,
    block_minecraft__purpur_stairs = 495,
    block_minecraft__prismarine_stairs = 383,
    block_minecraft__dark_prismarine_stairs = 385,
    block_minecraft__prismarine_brick_stairs = 384,
    block_minecraft__mossy_stone_brick_stairs = 629,
    block_minecraft__mossy_cobblestone_stairs = 631,
    block_minecraft__smooth_sandstone_stairs = 634,
    block_minecraft__smooth_quartz_stairs = 635,
    block_minecraft__polished_granite_stairs = 627,
    block_minecraft__polished_diorite_stairs = 630,
    block_minecraft__polished_andesite_stairs = 639,
    block_minecraft__stone_stairs = 633,
    block_minecraft__granite_stairs = 636,
    block_minecraft__diorite_stairs = 640,
    block_minecraft__andesite_stairs = 637,
    block_minecraft__end_stone_brick_stairs = 632,
    block_minecraft__red_nether_brick_stairs = 638,
    block_minecraft__smooth_red_sandstone_stairs = 628,
    block_minecraft__crimson_stairs = 716,
    block_minecraft__warped_stairs = 717,
    block_minecraft__blackstone_stairs = 744,
    block_minecraft__polished_blackstone_brick_stairs = 752,
    block_minecraft__polished_blackstone_stairs = 755,

    block_minecraft__chest = 147,
    block_minecraft__ender_chest = 270,
    block_minecraft__trapped_chest = 329,

    block_minecraft__redstone_wire = 148,

    block_minecraft__diamond_ore = 149,
    block_minecraft__diamond_block = 150,
    block_minecraft__crafting_table = 151,
    block_minecraft__fletching_table = 671,
    block_minecraft__cartography_table = 672,
    block_minecraft__smithing_table = 675,

    block_minecraft__wheat = 152,

    block_minecraft__farmland = 153,
    block_minecraft__grass_path = 498,

    block_minecraft__dispenser = 70,
    block_minecraft__furnace = 154,
    block_minecraft__dropper = 342,
    block_minecraft__blast_furnace = 670,
    block_minecraft__smoker = 669,

    block_minecraft__oak_sign = 155,
    block_minecraft__spruce_sign = 156,
    block_minecraft__birch_sign = 157,
    block_minecraft__jungle_sign = 158,
    block_minecraft__acacia_sign = 159,
    block_minecraft__dark_oak_sign = 160,
    block_minecraft__crimson_sign = 722,
    block_minecraft__warped_sign = 723,

    block_minecraft__oak_door = 161,
    block_minecraft__iron_door = 173,
    block_minecraft__spruce_door = 485,
    block_minecraft__birch_door = 486,
    block_minecraft__jungle_door = 487,
    block_minecraft__acacia_door = 488,
    block_minecraft__dark_oak_door = 489,
    block_minecraft__crimson_door = 720,
    block_minecraft__warped_door = 721,

    block_minecraft__ladder = 162,

    block_minecraft__rail = 163,
    block_minecraft__activator_rail = 341,

    block_minecraft__oak_wall_sign = 165,
    block_minecraft__spruce_wall_sign = 166,
    block_minecraft__birch_wall_sign = 167,
    block_minecraft__jungle_wall_sign = 168,
    block_minecraft__acacia_wall_sign = 169,
    block_minecraft__dark_oak_wall_sign = 170,
    block_minecraft__crimson_wall_sign = 724,
    block_minecraft__warped_wall_sign = 725,

    block_minecraft__lever = 171,

    block_minecraft__stone_pressure_plate = 172,
    block_minecraft__oak_pressure_plate = 174,
    block_minecraft__spruce_pressure_plate = 175,
    block_minecraft__birch_pressure_plate = 176,
    block_minecraft__jungle_pressure_plate = 177,
    block_minecraft__acacia_pressure_plate = 178,
    block_minecraft__dark_oak_pressure_plate = 179,
    block_minecraft__light_weighted_pressure_plate = 330,
    block_minecraft__heavy_weighted_pressure_plate = 331,

    block_minecraft__redstone_ore = 180,

    block_minecraft__stone_button = 183,
    block_minecraft__oak_button = 308,
    block_minecraft__spruce_button = 309,
    block_minecraft__birch_button = 310,
    block_minecraft__jungle_button = 311,
    block_minecraft__acacia_button = 312,
    block_minecraft__dark_oak_button = 313,

    block_minecraft__snow = 184,
    block_minecraft__snow_block = 186,

    block_minecraft__cactus = 187,
    block_minecraft__clay = 188,

    block_minecraft__sugar_cane = 189,
    block_minecraft__jukebox = 190,

    block_minecraft__oak_fence = 191,
    block_minecraft__oak_fence_gate = 250,
    block_minecraft__nether_brick_fence = 256,
    block_minecraft__spruce_fence_gate = 475,
    block_minecraft__birch_fence_gate = 476,
    block_minecraft__jungle_fence_gate = 477,
    block_minecraft__acacia_fence_gate = 478,
    block_minecraft__dark_oak_fence_gate = 479,
    block_minecraft__spruce_fence = 480,
    block_minecraft__birch_fence = 481,
    block_minecraft__jungle_fence = 482,
    block_minecraft__dark_oak_fence = 483,
    block_minecraft__acacia_fence = 484,

    block_minecraft__pumpkin = 192,
    block_minecraft__jack_o_lantern = 203,
    block_minecraft__carved_pumpkin = 202,

    block_minecraft__netherrack = 193,
    block_minecraft__soul_sand = 194,
    block_minecraft__glowstone = 200,

    block_minecraft__nether_portal = 201,

    block_minecraft__oak_trapdoor = 222,
    block_minecraft__iron_trapdoor = 379,
    block_minecraft__spruce_trapdoor = 223,
    block_minecraft__birch_trapdoor = 224,
    block_minecraft__jungle_trapdoor = 225,
    block_minecraft__acacia_trapdoor = 226,
    block_minecraft__dark_oak_trapdoor = 227,

    block_minecraft__brown_mushroom_block = 238,
    block_minecraft__red_mushroom_block = 239,
    block_minecraft__mushroom_stem = 240,

    block_minecraft__prismarine = 380,
    block_minecraft__prismarine_bricks = 381,
    block_minecraft__dark_prismarine = 382,

    block_minecraft__cake = 204,

    block_minecraft__repeater = 205,

    block_minecraft__iron_bars = 241,
    block_minecraft__glass_pane = 243,
    block_minecraft__white_stained_glass_pane = 359,
    block_minecraft__orange_stained_glass_pane = 360,
    block_minecraft__magenta_stained_glass_pane = 361,
    block_minecraft__light_blue_stained_glass_pane = 362,
    block_minecraft__yellow_stained_glass_pane = 363,
    block_minecraft__lime_stained_glass_pane = 364,
    block_minecraft__pink_stained_glass_pane = 365,
    block_minecraft__gray_stained_glass_pane = 366,
    block_minecraft__light_gray_stained_glass_pane = 367,
    block_minecraft__cyan_stained_glass_pane = 368,
    block_minecraft__purple_stained_glass_pane = 369,
    block_minecraft__blue_stained_glass_pane = 370,
    block_minecraft__brown_stained_glass_pane = 371,
    block_minecraft__green_stained_glass_pane = 372,
    block_minecraft__red_stained_glass_pane = 373,
    block_minecraft__black_stained_glass_pane = 374,

    block_minecraft__melon_block = 103,

    block_minecraft__melon = 244,
    block_minecraft__attached_pumpkin_stem = 245,
    block_minecraft__attached_melon_stem = 246,
    block_minecraft__pumpkin_stem = 247,
    block_minecraft__melon_stem = 248,


    block_minecraft__terracotta = 407,
    block_minecraft__white_terracotta = 343,
    block_minecraft__orange_terracotta = 344,
    block_minecraft__magenta_terracotta = 345,
    block_minecraft__light_blue_terracotta = 346,
    block_minecraft__yellow_terracotta = 347,
    block_minecraft__lime_terracotta = 348,
    block_minecraft__pink_terracotta = 349,
    block_minecraft__gray_terracotta = 350,
    block_minecraft__light_gray_terracotta = 351,
    block_minecraft__cyan_terracotta = 352,
    block_minecraft__purple_terracotta = 353,
    block_minecraft__blue_terracotta = 354,
    block_minecraft__brown_terracotta = 355,
    block_minecraft__green_terracotta = 356,
    block_minecraft__red_terracotta = 357,
    block_minecraft__black_terracotta = 358,

    block_minecraft__white_glazed_terracotta = 526,
    block_minecraft__orange_glazed_terracotta = 527,
    block_minecraft__magenta_glazed_terracotta = 528,
    block_minecraft__light_blue_glazed_terracotta = 529,
    block_minecraft__yellow_glazed_terracotta = 530,
    block_minecraft__lime_glazed_terracotta = 531,
    block_minecraft__pink_glazed_terracotta = 532,
    block_minecraft__gray_glazed_terracotta = 533,
    block_minecraft__light_gray_glazed_terracotta = 534,
    block_minecraft__cyan_glazed_terracotta = 535,
    block_minecraft__purple_glazed_terracotta = 536,
    block_minecraft__blue_glazed_terracotta = 537,
    block_minecraft__brown_glazed_terracotta = 538,
    block_minecraft__green_glazed_terracotta = 539,
    block_minecraft__red_glazed_terracotta = 540,
    block_minecraft__black_glazed_terracotta = 541,

    block_minecraft__vine = 249,

    block_minecraft__mycelium = 253,

    block_minecraft__lily_pad = 254,

    block_minecraft__nether_brick = 255,

    block_minecraft__nether_wart = 258,

    block_minecraft__enchanting_table = 259,
    block_minecraft__brewing_stand = 260,
    block_minecraft__cauldron = 261,
    block_minecraft__end_portal = 262,
    block_minecraft__end_portal_frame = 263,
    block_minecraft__end_stone = 264,
    block_minecraft__dragon_egg = 265,
    block_minecraft__redstone_lamp = 266,

    block_minecraft__cocoa = 267,
    block_minecraft__emerald_ore = 269,
    block_minecraft__tripwire_hook = 272,
    block_minecraft__tripwire_wire = 271,
    block_minecraft__emerald_block = 273,

    block_minecraft__beacon = 278,
    block_minecraft__carrots = 306,
    block_minecraft__potatoes = 307,

    block_minecraft__redstone_block = 334,
    block_minecraft__nether_quartz_ore = 335,
    block_minecraft__quartz_block = 337,
    block_minecraft__smooth_quartz = 473,
    block_minecraft__quartz_pillar = 339,
    block_minecraft__chiseled_quartz_block = 338,

    block_minecraft__command_block = 277,
    block_minecraft__repeating_command_block = 500,
    block_minecraft__chain_command_block = 501,
    block_minecraft__slime = 377,

    block_minecraft__anvil = 326,
    block_minecraft__chipped_anvil = 327,
    block_minecraft__damaged_anvil = 328,

    // adding a gap in the numbering of walls to keep them all
    // in one numbering block starting at 1792
    // all blocks between 1792 and 2047 are considered walls
    // this is because our check looks for the prefix 0b11100000000
    block_minecraft__andesite_wall = 661,
    block_minecraft__brick_wall = 654,
    block_minecraft__cobblestone_wall = 279,
    block_minecraft__diorite_wall = 665,
    block_minecraft__end_stone_brick_wall = 664,
    block_minecraft__granite_wall = 658,
    block_minecraft__mossy_cobblestone_wall = 280,
    block_minecraft__mossy_stone_brick_wall = 657,
    block_minecraft__nether_brick_wall = 660,
    block_minecraft__prismarine_wall = 655,
    block_minecraft__red_nether_brick_wall = 662,
    block_minecraft__red_sandstone_wall = 656,
    block_minecraft__sandstone_wall = 663,
    block_minecraft__stone_brick_wall = 659,
    block_minecraft__polished_blackstone_brick_wall = 753,
    block_minecraft__polished_blackstone_wall = 759,
    block_minecraft__blackstone_wall = 745,
    // end of walls
    block_minecraft__chorus_plant = 491,

    block_minecraft__comparator = 332,
    block_minecraft__daylight_detector = 333,
    block_minecraft__hopper = 336,

    block_minecraft__white_carpet = 391,
    block_minecraft__orange_carpet = 392,
    block_minecraft__magenta_carpet = 393,
    block_minecraft__light_blue_carpet = 394,
    block_minecraft__yellow_carpet = 395,
    block_minecraft__lime_carpet = 396,
    block_minecraft__pink_carpet = 397,
    block_minecraft__gray_carpet = 398,
    block_minecraft__light_gray_carpet = 399,
    block_minecraft__cyan_carpet = 400,
    block_minecraft__purple_carpet = 401,
    block_minecraft__blue_carpet = 402,
    block_minecraft__brown_carpet = 403,
    block_minecraft__green_carpet = 404,
    block_minecraft__red_carpet = 405,
    block_minecraft__black_carpet = 406,

    block_minecraft__chorus_flower = 492,
    block_minecraft__purpur_block = 493,
    block_minecraft__purpur_pillar = 494,

    block_minecraft__sea_lantern = 389,
    block_minecraft__hay_block = 390,
    block_minecraft__coal_block = 408,
    block_minecraft__packed_ice = 409,

    block_minecraft__red_sandstone = 448,
    block_minecraft__chiseled_red_sandstone = 449,
    block_minecraft__cut_red_sandstone = 450,

    block_minecraft__end_bricks = 496,
    block_minecraft__beetroots = 497,
    block_minecraft__sweet_berry_bush = 682,
    block_minecraft__frosted_ice = 502,
    block_minecraft__magma_block = 503,
    block_minecraft__nether_wart_block = 504,
    block_minecraft__red_nether_brick = 505,
    block_minecraft__bone_block = 506,

    block_minecraft__shulker_box = 509,
    block_minecraft__white_shulker_box = 510,
    block_minecraft__orange_shulker_box = 511,
    block_minecraft__magenta_shulker_box = 512,
    block_minecraft__light_blue_shulker_box = 513,
    block_minecraft__yellow_shulker_box = 514,
    block_minecraft__lime_shulker_box = 515,
    block_minecraft__pink_shulker_box = 516,
    block_minecraft__gray_shulker_box = 517,
    block_minecraft__light_gray_shulker_box = 518,
    block_minecraft__cyan_shulker_box = 519,
    block_minecraft__purple_shulker_box = 520,
    block_minecraft__blue_shulker_box = 521,
    block_minecraft__brown_shulker_box = 522,
    block_minecraft__green_shulker_box = 523,
    block_minecraft__red_shulker_box = 524,
    block_minecraft__black_shulker_box = 525,

    block_minecraft__observer = 508,

    block_minecraft__ancient_debris = 735,
    block_minecraft__basalt = 196,
    block_minecraft__polished_basalt = 197,
    block_minecraft__soul_campfire = 681,
    block_minecraft__campfire = 680,
    block_minecraft__blackstone = 743,
    block_minecraft__netherite_block = 734,

    block_minecraft__warped_nylium = 687,
    block_minecraft__crimson_nylium = 696,
    block_minecraft__soul_soil = 195,

    block_minecraft__bell = 677,

    block_minecraft__beehive = 731,
    block_minecraft__bee_nest = 730,
    block_minecraft__honeycomb_block = 733,
    block_minecraft__honey_block = 732,

    block_minecraft__dried_kelp_block = 576,
    block_minecraft__scaffolding = 666,

    block_minecraft__white_concrete = 542,
    block_minecraft__orange_concrete = 543,
    block_minecraft__magenta_concrete = 544,
    block_minecraft__light_blue_concrete = 545,
    block_minecraft__yellow_concrete = 546,
    block_minecraft__lime_concrete = 547,
    block_minecraft__pink_concrete = 548,
    block_minecraft__gray_concrete = 549,
    block_minecraft__light_gray_concrete = 550,
    block_minecraft__cyan_concrete = 551,
    block_minecraft__purple_concrete = 552,
    block_minecraft__blue_concrete = 553,
    block_minecraft__brown_concrete = 554,
    block_minecraft__green_concrete = 555,
    block_minecraft__red_concrete = 556,
    block_minecraft__black_concrete = 557,

    block_minecraft__white_concrete_powder = 558,
    block_minecraft__orange_concrete_powder = 559,
    block_minecraft__magenta_concrete_powder = 560,
    block_minecraft__light_blue_concrete_powder = 561,
    block_minecraft__yellow_concrete_powder = 562,
    block_minecraft__lime_concrete_powder = 563,
    block_minecraft__pink_concrete_powder = 564,
    block_minecraft__gray_concrete_powder = 565,
    block_minecraft__light_gray_concrete_powder = 566,
    block_minecraft__cyan_concrete_powder = 567,
    block_minecraft__purple_concrete_powder = 568,
    block_minecraft__blue_concrete_powder = 569,
    block_minecraft__brown_concrete_powder = 570,
    block_minecraft__green_concrete_powder = 571,
    block_minecraft__red_concrete_powder = 572,
    block_minecraft__black_concrete_powder = 573,

    block_minecraft__jigsaw = 727,
    block_minecraft__structure_block = 726,
    block_minecraft__warped_wart_block = 689,

    block_minecraft__shroomlight = 698,
    block_minecraft__twisting_vines = 701,
    block_minecraft__twisting_vines_plant = 702,
    block_minecraft__weeping_vines = 699,
    block_minecraft__weeping_vines_plant = 700,

    block_minecraft__grindstone = 673,
    block_minecraft__loom = 667,
    block_minecraft__stonecutter = 676,
    block_minecraft__lectern = 674,

    block_minecraft__composter = 728,

    block_minecraft__bamboo = 622,

    block_minecraft__bamboo_sapling = 621,

    block_minecraft__warped_fungus = 688,
    block_minecraft__crimson_fungus = 697,
    block_minecraft__warped_roots = 690,
    block_minecraft__crimson_roots = 703,

    block_minecraft__lantern = 678,

    block_minecraft__crimson_fence = 710,
    block_minecraft__warped_fence = 711,
    block_minecraft__crimson_fence_gate = 714,
    block_minecraft__warped_fence_gate = 715,

    block_minecraft__gilded_blackstone = 754,

    //TODO
    block_minecraft__double_plant = 175,
    block_minecraft__sapling = 116,
    
    
    // block_minecraft__lit_furnace = 62,
    // block_minecraft__lit_redstone_ore = 74,
   
    block_minecraft__monster_egg = 97,
    block_minecraft__stonebrick = 98,
    block_minecraft__lit_redstone_lamp = 124,
    block_minecraft__flower_pot = 140,
    block_minecraft__skull = 144,
    block_minecraft__stained_hardened_clay = 159,
    block_minecraft__barrier = 166,
    block_minecraft__hardened_clay = 172,
    
    block_minecraft__standing_banner = 176,
    block_minecraft__wall_banner = 177,
    block_minecraft__end_rod = 198,
    block_minecraft__structure_void = 217,
    block_minecraft__end_gateway = 209,
    // 1.16 stuff
    // block_minecraft__blast_furnace lit 11363
    // block_minecraft__smoker lit = 11365,
    // 1.15 blocks below
};

typedef uint16_t mc_block_t;

enum mc_item_id {
    item_iron_shovel = 256,
    item_iron_pickaxe = 257,
    item_iron_axe = 258,
    item_flint_and_steel = 259,
    item_apple = 260,
    item_bow = 261,
    item_arrow = 262,
    item_coal = 263,
    item_diamond = 264,
    item_iron_ingot = 265,
    item_gold_ingot = 266,
    item_iron_sword = 267,
    item_wooden_sword = 268,
    item_wooden_shovel = 269,
    item_wooden_pickaxe = 270,
    item_wooden_axe = 271,
    item_stone_sword = 272,
    item_stone_shovel = 273,
    item_stone_pickaxe = 274,
    item_stone_axe = 275,
    item_diamond_sword = 276,
    item_diamond_shovel = 277,
    item_diamond_pickaxe = 278,
    item_diamond_axe = 279,
    item_stick = 280,
    item_bowl = 281,
    item_mushroom_stew = 282,
    item_golden_sword = 283,
    item_golden_shovel = 284,
    item_golden_pickaxe = 285,
    item_golden_axe = 286,
    item_string = 287,
    item_feather = 288,
    item_gunpowder = 289,
    item_wooden_hoe = 290,
    item_stone_hoe = 291,
    item_iron_hoe = 292,
    item_diamond_hoe = 293,
    item_golden_hoe = 294,
    item_wheat_seeds = 295,
    item_wheat = 296,
    item_bread = 297,
    item_leather_helmet = 298,
    item_leather_chestplate = 299,
    item_leather_leggings = 300,
    item_leather_boots = 301,
    item_chainmail_helmet = 302,
    item_chainmail_chestplate = 303,
    item_chainmail_leggings = 304,
    item_chainmail_boots = 305,
    item_iron_helmet = 306,
    item_iron_chestplate = 307,
    item_iron_leggings = 308,
    item_iron_boots = 309,
    item_diamond_helmet = 310,
    item_diamond_chestplate = 311,
    item_diamond_leggings = 312,
    item_diamond_boots = 313,
    item_golden_helmet = 314,
    item_golden_chestplate = 315,
    item_golden_leggings = 316,
    item_golden_boots = 317,
    item_flint = 318,
    item_porkchop = 319,
    item_cooked_porkchop = 320,
    item_painting = 321,
    item_golden_apple = 322,
    item_sign = 323,
    item_wooden_door = 324,
    item_bucket = 325,
    item_water_bucket = 326,
    item_lava_bucket = 327,
    item_minecart = 328,
    item_saddle = 329,
    item_iron_door = 330,
    item_redstone = 331,
    item_snowball = 332,
    item_boat = 333,
    item_leather = 334,
    item_milk_bucket = 335,
    item_brick = 336,
    item_clay_ball = 337,
    item_reeds = 338,
    item_paper = 339,
    item_book = 340,
    item_slime_ball = 341,
    item_chest_minecart = 342,
    item_furnace_minecart = 343,
    item_egg = 344,
    item_compass = 345,
    item_fishing_rod = 346,
    item_clock = 347,
    item_glowstone_dust = 348,
    item_fish = 349,
    item_cooked_fish = 350,
    item_dye = 351,
    item_bone = 352,
    item_sugar = 353,
    item_cake = 354,
    item_bed = 355,
    item_repeater = 356,
    item_cookie = 357,
    item_filled_map = 358,
    item_shears = 359,
    item_melon = 360,
    item_pumpkin_seeds = 361,
    item_melon_seeds = 362,
    item_beef = 363,
    item_cooked_beef = 364,
    item_chicken = 365,
    item_cooked_chicken = 366,
    item_rotten_flesh = 367,
    item_ender_pearl = 368,
    item_blaze_rod = 369,
    item_ghast_tear = 370,
    item_gold_nugget = 371,
    item_nether_wart = 372,
    item_potion = 373,
    item_glass_bottle = 374,
    item_spider_eye = 375,
    item_fermented_spider_eye = 376,
    item_blaze_powder = 377,
    item_magma_cream = 378,
    item_brewing_stand = 379,
    item_cauldron = 380,
    item_ender_eye = 381,
    item_speckled_melon = 382,
    item_spawn_egg = 383,
    item_experience_bottle = 384,
    item_fire_charge = 385,
    item_writable_book = 386,
    item_written_book = 387,
    item_emerald = 388,
    item_item_frame = 389,
    item_flower_pot = 390,
    item_carrot = 391,
    item_potato = 392,
    item_baked_potato = 393,
    item_poisonous_potato = 394,
    item_map = 395,
    item_golden_carrot = 396,
    item_skull = 397,
    item_carrot_on_a_stick = 398,
    item_nether_star = 399,
    item_pumpkin_pie = 400,
    item_fireworks = 401,
    item_firework_charge = 402,
    item_enchanted_book = 403,
    item_comparator = 404,
    item_netherbrick = 405,
    item_quartz = 406,
    item_tnt_minecart = 407,
    item_hopper_minecart = 408,
    item_prismarine_shard = 409,
    item_prismarine_crystals = 410,
    item_rabbit = 411,
    item_cooked_rabbit = 412,
    item_rabbit_stew = 413,
    item_rabbit_foot = 414,
    item_rabbit_hide = 415,
    item_armor_stand = 416,
    item_iron_horse_armor = 417,
    item_golden_horse_armor = 418,
    item_diamond_horse_armor = 419,
    item_lead = 420,
    item_name_tag = 421,
    item_command_block_minecraft__minecart = 422,
    item_mutton = 423,
    item_cooked_mutton = 424,
    item_banner = 425,
    item_end_crystal = 426,
    item_spruce_door = 427,
    item_birch_door = 428,
    item_jungle_door = 429,
    item_acacia_door = 430,
    item_dark_oak_door = 431,
    item_chorus_fruit = 432,
    item_popped_chorus_fruit = 433,
    item_beetroot = 434,
    item_beetroot_seeds = 435,
    item_beetroot_soup = 436,
    item_dragon_breath = 437,
    item_splash_potion = 438,
    item_spectral_arrow = 439,
    item_tipped_arrow = 440,
    item_lingering_potion = 441,
    item_shield = 442,
    item_elytra = 443,
    item_spruce_boat = 444,
    item_birch_boat = 445,
    item_jungle_boat = 446,
    item_acacia_boat = 447,
    item_dark_oak_boat = 448,
    item_totem_of_undying = 449,
    item_shulker_shell = 450,
    item_iron_nugget = 452,
    item_knowledge_book = 453,
    item_record_13 = 2256,
    item_record_cat = 2257,
    item_record_blocks = 2258,
    item_record_chirp = 2259,
    item_record_far = 2260,
    item_record_mall = 2261,
    item_record_mellohi = 2262,
    item_record_stal = 2263,
    item_record_strad = 2264,
    item_record_ward = 2265,
    item_record_11 = 2266,
    item_record_wait = 2267
};

typedef uint16_t mc_item_t;
#endif
